
---
- name: "Update binary files from github.com releases yt-dlp.."
  hosts:
    - localhost
  become: true
  gather_facts: false
  vars:
    repository_owner: "yt-dlp"
    project_name: "yt-dlp"
    release_file_name: "yt-dlp"
    destination_file_name: "yt-dlp"
    destination_directory: "/usr/local/bin"
    download_dir: "/tmp"
  tasks:
    - name: Set variables to artefacts..
      set_fact:
        github_repo_url: "https://github.com/{{ repository_owner  }}/{{ project_name }}"

    - name: Get GitHub Releases
      uri:
        url: "https://api.github.com/repos/{{ repository_owner  }}/{{ project_name }}/releases/latest"
        return_content: yes
        headers:
          Accept: "application/vnd.github.v3+json"
      register: github_release

    - name: Extract latest tag
      set_fact:
        latest_tag: "{{ github_release.json.tag_name }}"

    - name: Display latest tag
      debug:
        msg: "Latest tag: {{ latest_tag }}"
  
    - name: Download {{ project_name }}
      get_url:
        url: "{{ github_repo_url }}/releases/download/{{ latest_tag }}/{{ release_file_name }}"
        dest: "{{ download_dir }}/{{ release_file_name }}"

    - name: Display downloaded version
      debug:
        msg: "{{ release_file_name }}} version {{ latest_tag }} downloaded to {{ download_dir }}/{{ release_file_name }}"

    - name: Move latest release of {{ destination_file_name }} to its destination on local filesystem.. ({{ destination_directory }}/{{ destination_file_name }})
      ansible.builtin.copy:
        src: "{{ download_dir }}/{{ release_file_name }}"
        dest: "{{ destination_directory }}/{{ destination_file_name }}"
        owner: "root"
        group: "root"
        mode: "0755"
